#development version of configurations
server:
  port: 8083

spring:
  application:
    name: project7

  #databse config
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  #jpa , hibernate config
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET:dev_secret_key_super_long_random_string_256bit_minimum_!@#123}
    issuer: ${JWT_ISSUER:api.substring.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
